  services:
    rabbitmq:
      image: rabbitmq:3-management

      ports:
        - 15672:15672
        - 5672:5672

    worker:
      image: allisyonok/worker
      depends_on:
        - rabbitmq

    pathfinder:
      image: allisyonok/pathfinder
      depends_on:
        - rabbitmq
        - worker
      ports:
        - '9000:9000'
        