// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pathfinder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PathFinderClient is the client API for PathFinder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PathFinderClient interface {
	GetPath(ctx context.Context, in *GetPathRequest, opts ...grpc.CallOption) (*GetPathResponse, error)
}

type pathFinderClient struct {
	cc grpc.ClientConnInterface
}

func NewPathFinderClient(cc grpc.ClientConnInterface) PathFinderClient {
	return &pathFinderClient{cc}
}

func (c *pathFinderClient) GetPath(ctx context.Context, in *GetPathRequest, opts ...grpc.CallOption) (*GetPathResponse, error) {
	out := new(GetPathResponse)
	err := c.cc.Invoke(ctx, "/pathfinder.PathFinder/GetPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PathFinderServer is the server API for PathFinder service.
// All implementations must embed UnimplementedPathFinderServer
// for forward compatibility
type PathFinderServer interface {
	GetPath(context.Context, *GetPathRequest) (*GetPathResponse, error)
	mustEmbedUnimplementedPathFinderServer()
}

// UnimplementedPathFinderServer must be embedded to have forward compatible implementations.
type UnimplementedPathFinderServer struct {
}

func (UnimplementedPathFinderServer) GetPath(context.Context, *GetPathRequest) (*GetPathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPath not implemented")
}
func (UnimplementedPathFinderServer) mustEmbedUnimplementedPathFinderServer() {}

// UnsafePathFinderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PathFinderServer will
// result in compilation errors.
type UnsafePathFinderServer interface {
	mustEmbedUnimplementedPathFinderServer()
}

func RegisterPathFinderServer(s grpc.ServiceRegistrar, srv PathFinderServer) {
	s.RegisterService(&PathFinder_ServiceDesc, srv)
}

func _PathFinder_GetPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PathFinderServer).GetPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pathfinder.PathFinder/GetPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PathFinderServer).GetPath(ctx, req.(*GetPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PathFinder_ServiceDesc is the grpc.ServiceDesc for PathFinder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PathFinder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pathfinder.PathFinder",
	HandlerType: (*PathFinderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPath",
			Handler:    _PathFinder_GetPath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pathfinder.proto",
}
